version: '{build}'
os: Visual Studio 2015
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  project: build/Build.proj
  verbosity: normal
test:
  assemblies: test/**/*.Tests.dll
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: PWCeOQ12fgAhPiBjgkBAqHbvaPQArarsO2sI+8KCeXjBjE+AHaMIMW8b7efmDzQ6
  skip_symbols: true
  artifact: artifacts/packages/*.nupkg